name: test
on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main"]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install --force
        working-directory: noses/
      - name: Run tests
        run: npm run test-ci
        working-directory: noses/